services:
    bot:
        image: ghcr.io/krau/quote-bot:main
        restart: always
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "3"
        env_file: .env
        command: node index.js
    api:
        image: ghcr.io/lyosu/quote-api:latest
        restart: always
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "3"
        env_file: .env
        command: node index.js
        volumes:
            - ./data/fonts:/app/assets/fonts
